### ISSUE TITLE
Can we merge videos like tiles

### ISSUE THREAD

**Issue by Arslan007** [Datt1994/DPVideoMerger#1]
First of all nice work. Keep it UP 👍 
Secondly, my question is can we merge the videos like tiles. I have one screen where I can choose 4 videos and select 4 videos then on merge all videos merge like tiles and display in video like all playing on thier on tile

**Comment by Datt1994** [comment]
I added new method (**gridMergeVideosWithFileURLs**:) in latest commit check it out.

**Comment by Arslan007** [comment]
Wonderfull 💯
