### ISSUE TITLE
After complete how to repeat video?

### ISSUE THREAD

**Issue by DixPatel009** [Datt1994/DPVideoMerger#4]
I Think This is not issue. 

we seclect 4 video for grid.
1st video time is 0.4 second.
2nd video time is 0.8 second.
3rd video time is 1.2 second.
4th video time is 0.5 second.

so now your code final video playing max time (based on ex 1.2 second) and other video stop playing after end.

so we need to repeat other videos this is possible?

just give suggestion for this.

Thanks in advance.

**Comment by Datt1994** [comment]
@DixPatel009 Please check updated repository.
