### ISSUE TITLE
It is working with mkv ? seems not

### ISSUE THREAD

**Issue by Geremp** [Datt1994/DPVideoMerger#5]
Hello, 

I try to use your lib to merge mkv file.
I get an error.
DO you know if your lib is working for mkv file ?

**Comment by Datt1994** [comment]
Hi @Geremp ,

I am using AVKit to merge videos, So right now only following Video file supported.
    "video/3gpp2",
    "video/quicktime",
    "video/mp4",
    "video/avi",
    "video/x-m4v",
    "video/3gpp",
Use this method to check if you video file supported or not :- `[AVURLAsset audiovisualMIMETypes];`
I added error message for same in updated repo please check.
